---
- name: add docker key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- name: add docker repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    update_cache: true

- name: Install Docker
  apt:
    name: docker-ce
    state: present
    update_cache: true

- name: Enable docker service
  systemd:
    name: docker
    enabled: yes

- name: Start docker service
  systemd:
    name: docker
    state: started

- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755
